package com.utility;

public enum ApplicationConfigurationEnum {
    SMTP_HOST, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD, SMTP_TLS_ENABLED, SMTP_AUTHENTICATION, SMTP_EMAIL_EXEC,
    SMS_URL, SMS_USERNAME, SMS_PASSWORD, SMS_COST_CENTER_ID, SMS_APP_ID, SMS_FROM, SMS_TYPE_ID, SMS_DLR_ID, 
    ANDROID_VERSION, ANDROID_DOWNLOAD_URL, HT_VERSION, HT_FILE_VERSION,
    ALLOW_ALERT_NOTIFICATION, APP_NAME, APP_URL, ALLOW_SHARING,
    ALLOW_RISK_NOTIFICATION, ALLOW_MAIL_NOTIFICATION, ALLOW_SMS_NOTIFICATION, PUBLIC_CONTENT,
    USE_DFG
    
}
